name:                pi-calculus
version:             0.1.0.0
github:              "slemus9/pi-calculus"
license:             BSD3
author:              "Sebastián Lemus Cadena"
maintainer:          "example@example.com"
copyright:           "2023 Sebastián Lemus Cadena"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/slemus9/pi-calculus#readme>

dependencies:
- base >= 4.7 && < 5
- text
- parsec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  pi-calculus-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pi-calculus

tests:
  pi-calculus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pi-calculus
    - tasty
    - tasty-hunit
    - tasty-quickcheck
