name: Build and Validate

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout working directory
        uses: actions/checkout@v3

      - name: Validate formatting
        uses: haskell-actions/run-fourmolu@v9
        with:
          version: "0.13.0.0"

      - name: Build and test
        uses: freckle/stack-action@v4
        with:
          pedantic: true
          test: true
